export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const SELECT = "SELECT";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const SET_SELECTED_CATEGORY ="SET_SELECTED_CATEGORY"
export const FETCH_PRODUCTS_SUCCESS ="FETCH_PRODUCTS_SUCCESS"

export const DECREASE = "DECREASE_QUANTITY";
export const INCREASE = "INCREASE";
export const UPDATE = "UPDATE";
export const UPDATE_PRODUCT_IN_STOCK = 'UPDATE_PRODUCT_IN_STOCK';

